const mongoose = require("mongoose");
const orderSchema = mongoose.Schema(
  {
    id: { type: Number },
    referal_id: { type: String },
    parent_id: { type: Number },
    status: { type: String },
    currency: { type: String },
    version: { type: String },
    prices_include_tax: { type: Boolean },
    date_created: { type: String },
    date_modified: { type: String },
    discount_total: { type: String },
    discount_tax: { type: String },
    shipping_total: { type: String },
    shipping_tax: { type: String },
    cart_tax: { type: String },
    total: { type: String },
    total_tax: { type: String },
    customer_id: { type: Number },
    order_key: { type: String },
    billing: { type: Object },
    shipping: { type: Object },
    payment_method: { type: String },
    payment_method_title: { type: String },
    transaction_id: { type: String },
    customer_ip_address: { type: String },
    customer_user_agent: { type: String },
    created_via: { type: String },
    customer_note: { type: String },
    date_completed: { type: Object },
    date_paid: { type: Object },
    cart_hash: { type: String },
    number: { type: String },
    meta_data: { type: Array, default: [] },
    line_items: { type: Array, default: [] },
    tax_lines: { type: Array, default: [] },
    shipping_lines: { type: Array, default: [] },
    fee_lines: { type: Array, default: [] },
    coupon_lines: { type: Array, default: [] },
    refunds: { type: Array, default: [] },
    payment_url: { type: String },
    is_editable: { type: Boolean },
    needs_payment: { type: Boolean },
    needs_processing: { type: Boolean },
    date_created_gmt: { type: String },
    date_modified_gmt: { type: String },
    date_completed_gmt: { type: Object },
    date_paid_gmt: { type: Object },
    currency_symbol: { type: String },
    _links: { type: Object },
  },
  { timestamps: true }
);

const orderModel = mongoose.model("orders", orderSchema);
module.exports = orderModel;
